<?php
namespace jc\test\unit\testcase\jc\fs\imp;


/**
 * Test class for LocalFile.
 * Generated by PHPUnit on 2011-08-12 at 16:39:19.
 */
class LocalFile extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LocalFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    	$aFileSystem = new \jc\fs\imp\LocalFileSystem('/home/elephant/文档/JeCat/github/framework-test/unit/data/locale');
    	if(! $aFileSystem ->exists('/a.txt')){
    		$aFileSystem -> createFile('/a.txt');
    	}
        $this->object = $aFileSystem->findFile('/a.txt');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    	$this->object->delete();
    }

    /**
     * @todo Implement testOpenReader().
     */
    public function testOpenReader()
    {
    	$str = 'hahahahahaha';
    	$this->object->openWriter()->write($str);
        $this->assertEquals(
        		$this->object->openReader()->read(strlen($str)),
        		$str
        );
    }

    /**
     * @todo Implement testOpenWriter().
     */
    public function testOpenWriter()
    {
        $str = 'hahahahahaha';
    	$this->object->openWriter()->write($str);
        $this->assertEquals(
        		$this->object->openReader()->read(strlen($str)),
        		$str
        );
    }

    /**
     * @todo Implement testLength().
     */
    public function testLength()
    {
        $str = 'hahahahahaha';
    	$this->object->openWriter()->write($str);
        $this->assertEquals(
        		$this->object->length(),
        		strlen($str)
        );
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
    	$this->object->delete();
    	$this->assertFalse(
    			$this->object->exists()
    	);
    }

    /**
     * @todo Implement testHash().
     */
    public function testHash()
    {
        $this->assertEquals(
        		$this->object->hash(),
        		md5('/home/elephant/文档/JeCat/github/framework-test/unit/data/locale/a.txt')
        );
    }

    /**
     * @todo Implement testIncludeFile().
     */
    public function testIncludeFile()
    {
        $this->assertTrue(true);
    }

    /**
     * @todo Implement testCreate().
     */
    public function testCreate()
    {
        $this->object->delete();
    	$this->assertFalse(
    			$this->object->exists()
    	);
    	$this->object->create();
    	$this->assertTrue(
    			$this->object->exists()
    	);
    }

    /**
     * @todo Implement testExists().
     */
    public function testExists()
    {
    	$this->object->delete();
    	$this->assertFalse(
    			$this->object->exists()
    	);
    	$this->object->create();
    	$this->assertTrue(
    			$this->object->exists()
    	);
    }
}
?>
